--------------------------------------------------------------------------------
Processing file 'utils.py'
 outputting to 'utils.py'
--------------------------------------------------------------------------------

Failed to parse 'utils.py'

Traceback (most recent call last):
  File "tf_upgrade.py", line 539, in process_opened_file
    parsed_ast = ast.parse("".join(lines))
  File "/home/hume/anaconda3/lib/python3.6/ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 60
    output_q = max_pooling(input_q)
                                  ^
TabError: inconsistent use of tabs and spaces in indentation

